### ISSUE TITLE
Include Quality Images up Through Step Functions Section

### ISSUE THREAD

**Issue by T-monius** [maestro-framework/maestro-framework.github.io#3]
Currently have images up to the AWS Step Functions section included in the `assets/images` directory. Images to include the Step functions portion are also in the directory but not of good quality. The only ones that may be usable are those that represent the ASL and Workflow diagrams as side-by-sides; the white PNG backdrop may be acceptable for those images.

Need to replace the images in the directory when available such that they don't have a white but transparent background.

**Comment by zklamm** [comment]
I have updated several images (see PR #5) to be transparent PNGs. I'll wait on updating the ASL/workflow diagrams until we have a color scheme decided.

**Comment by T-monius** [comment]
Awesome!
